name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: |
        cd docs
        npm install
    
    - name: Build release
      run: |
        cd docs
        npm run build
        ls
    
    - name: Compress release
      run: |
        cd docs/build
        tar -czvf build.tar.gz ./*

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: false
        prerelease: false
        automatic_release_tag: continuous
        title: Continuous release
        files: |
          build.tar.gz
