# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: cd docs
    - run: npm install
    - run: npm test
    - run: ls

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: Bottles-devel-x86_64.AppImage
