# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: |
        cd docs
        npm install
    
    - name: Build release
      run: |
        cd docs
        npm run build
        ls

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: docs/dist/
